"""venvstacks layered environment site customization script

* Calls `site.addsitedir` for any configured Python path entries
* Calls `os.add_dll_directory` for any configured Windows dynlib paths

This venv module is automatically generated by the post-installation script.
"""


# Allow loading modules and packages from linked environments
from site import addsitedir
addsitedir('C:\\Users\\user\\.lmstudio\\extensions\\backends\\vendor\\_amphibian\\cpython3.11-win-x86@6\\Lib\\site-packages')

# Allow loading misplaced DLLs on Windows
from os import add_dll_directory
# Skipping 'C:\\Users\\user\\.lmstudio\\extensions\\backends\\vendor\\_amphibian\\cpython3.11-win-x86@6\\Library\\bin' (no such directory)
